// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalGalaxy.DataAccess;

#nullable disable

namespace PortalGalaxy.DataAccess.Migrations.PortalGalaxyDb
{
    [DbContext(typeof(PortalGalaxyDbContext))]
    [Migration("20250909224700_GalaxyMigrations")]
    partial class GalaxyMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalGalaxy.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("date");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Situacion")
                        .HasColumnType("int");

                    b.Property<int>("TallerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AlumnoId" }, "IX_Inscripcion_AlumnoId");

                    b.HasIndex(new[] { "TallerId" }, "IX_Inscripcion_TallerId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_Instructor_CategoriaId");

                    b.HasIndex(new[] { "NroDocumento" }, "IX_Instructor_NroDocumento");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Taller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortadaUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Situacion")
                        .HasColumnType("int");

                    b.Property<string>("TemarioUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_Taller_CategoriaId");

                    b.HasIndex(new[] { "InstructorId" }, "IX_Taller_InstructorId");

                    b.HasIndex(new[] { "Nombre" }, "IX_Taller_Nombre");

                    b.ToTable("Taller");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Inscripcion", b =>
                {
                    b.HasOne("PortalGalaxy.Entities.Alumno", "Alumno")
                        .WithMany("Inscripcions")
                        .HasForeignKey("AlumnoId")
                        .IsRequired();

                    b.HasOne("PortalGalaxy.Entities.Taller", "Taller")
                        .WithMany("Inscripcions")
                        .HasForeignKey("TallerId")
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Taller");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Instructor", b =>
                {
                    b.HasOne("PortalGalaxy.Entities.Categoria", "Categoria")
                        .WithMany("Instructors")
                        .HasForeignKey("CategoriaId")
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Taller", b =>
                {
                    b.HasOne("PortalGalaxy.Entities.Categoria", "Categoria")
                        .WithMany("Tallers")
                        .HasForeignKey("CategoriaId")
                        .IsRequired();

                    b.HasOne("PortalGalaxy.Entities.Instructor", "Instructor")
                        .WithMany("Tallers")
                        .HasForeignKey("InstructorId")
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Alumno", b =>
                {
                    b.Navigation("Inscripcions");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Categoria", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Tallers");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Instructor", b =>
                {
                    b.Navigation("Tallers");
                });

            modelBuilder.Entity("PortalGalaxy.Entities.Taller", b =>
                {
                    b.Navigation("Inscripcions");
                });
#pragma warning restore 612, 618
        }
    }
}
